# Generated by Django 5.2.1 on 2025-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('developpement', 'Developpement'), ('design', 'Design & Infographie')], default='developpement', max_length=20),
        ),
    ]
